apiVersion: velero.io/v1
kind: Backup
metadata:
  name: test-backup
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  hooks: {}
  includedNamespaces:
  - test-csi
  storageLocation: dpa-sample-1
  ttl: 720h0m0s
