apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: dpa-sample
spec:
  configuration:
    velero:
      defaultPlugins:
      - openshift
      - aws
      - csi
  backupLocations:
    - name: default
      velero:
        provider: aws
        default: true
        objectStorage:
          bucket: test
          prefix: mytest
        config:
          region: minio
          profile: "default"
          insecureSkipTLSVerify: "true"
          s3Url: "http://s3.openshift.training:9000"
          s3ForcePathStyle: "true"
        credential:
          key: cloud
          name: cloud-credentials
