apiVersion: v1
kind: Pod
metadata:
  name: example-fs-rwx
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox:1.24
      command: ["/bin/sh", "-c", "while true ; do sleep 2 ; done"]
      volumeMounts:
      - mountPath: "/mnt/backup"
        name: data
  restartPolicy: Never
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc-test-rwx-csi
