apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-rwx-csi
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: thin-csi
