apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-csi
spec:
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: thin-csi
